spring:
  datasource:
    driverClassName: org.h2.Driver
    password:
    url: jdbc:h2:mem:til;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    initialization-mode: always
  h2:
    console:
      enabled: true
      path: /h2-console